# Generated by Django 5.0.2 on 2024-02-28 22:34

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=64)),
                ('name', models.CharField()),
                ('size', models.IntegerField()),
                ('date_uploaded', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
    ]
