# Generated by Django 5.0.2 on 2024-03-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_uploaded',
            field=models.BigIntegerField(),
        ),
    ]
