# Generated by Django 5.0.2 on 2024-03-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_file_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(max_length=255),
        ),
    ]
